# Generated by Django 3.2 on 2021-04-27 15:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerceApp', '0008_auto_20210225_1612'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderedItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordered', models.BooleanField(default=False)),
                ('quantity', models.IntegerField(default=1)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommerceApp.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommerceApp.user')),
            ],
        ),
    ]
