# Generated by Django 3.2 on 2021-05-05 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerceApp', '0012_alter_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='target',
            field=models.CharField(default='mens', max_length=255),
        ),
    ]
